# Command to start the environment: 
# docker-compose down  --remove-orphans
# docker-compose up --build -d

version: "3.7"

services:
  sql:
    user: root
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=PASS-WORD_123
      - MSSQL_PID=Developer
      - ACCEPT_EULA=1
    stdin_open: true
    tty: true
  
  api:
    depends_on:
      - sql
    build:
      context: .
      dockerfile: ./todos.api/Dockerfile
      args:
        - TARGET_RUNTIME=${TARGET_RUNTIME}
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ConnectionStrings:Database=Server=sql;Database=Todos;User Id=SA;Password=PASS-WORD_123;
      
    entrypoint: bash -c "sleep 10 && dotnet todos.api.dll"